# Catppuccin-Mocha
include current-theme.conf

# Font
font_family Dank Mono
bold_font        auto
italic_font      auto
bold_italic_font auto

font_size 15.0

# setup fallback for unicode characters if needed
# symbol_map U+E0A0-U+E0A3,U+E0C0-U+E0C7 PowerlineSymbols

scrollback_lines 5000
enable_audio_bell no

window_padding_width 0 0 -1 0
modify_font baseline -3px
modify_font cell_height 130%

hide_window_decorations titlebar-only

