require("user.launch")
require("user.options")
require("user.keymaps")
require("user.autocmds")

-- Specs for plugins.
spec("user.colorscheme")
spec("user.devicons")
spec("user.treesitter")
spec("user.mason")
spec("user.schemastore")
spec("user.lspconfig")
spec("user.which-key")
spec("user.cmp")
spec("user.none-ls")
spec("user.telescope")
spec ("user.nvim-tree")
spec("user.comment")
spec("user.lualine")
spec("user.navic")
spec("user.breadcrumbs")
spec("user.harpoon")
spec("user.illuminate")
spec("user.neotest")
spec("user.gitsigns")
spec("user.indentline")
spec("user.toggleterm")

-- Extras
spec("user.extras.copilot")
spec("user.extras.neoscroll")
spec("user.extras.tabby")
spec("user.extras.oil")
spec("user.extras.ufo")
spec("user.extras.cellular-automaton")
spec("user.extras.autopairs")
spec("user.extras.fidget")
spec("user.extras.bqf")
spec("user.extras.colorizer")
spec("user.extras.dressing")
spec("user.extras.modicator")
spec("user.extras.navbuddy")

require("user.lazy")
